name: 'RunTests'

on:
  - push

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Excluding Python 3.7 and 3.10 since Superset 1.5 doesn't install on 3.7 or 3.10.  Hopefully we can
        # add 3.10 soon
        python-version:
          - '3.8'
          - '3.9'
        clickhouse-version:
          - '21.8'
          - '22.3'
          - latest

    services:
      clickhouse:
        image: clickhouse/clickhouse-server:${{ matrix.clickhouse-version }}
        ports:
          - 8123:8123
        options: --ulimit nofile=262144:262144

    name: Py=${{ matrix.python-version }} CH=${{ matrix.clickhouse-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest setuptools wheel requests pytz
          pip install -r test_requirements.txt
      - name: Build cython extensions
        run: python setup.py build_ext --inplace
      - name: Run tests
        run: pytest --no-docker tests
          




